### ISSUE TITLE
status.sh

### ISSUE THREAD

**Issue by Alienpruts** [kewljuice/maersk-line#1]
I do not understand quite clearly what the purpose of this shell script would be?

For instance :

1) Checking versions is fine, but you should first check if the programs are installed (for instance, docker machine is quite unnecessary on Linux machines :) )

2) Doing a "docker images" and a "docker ps -a" does not prove a thing : the amount of images / containers is irrelevant to the functioning of Docker (and might confuse users of this Docker instance, they will see their own images / containers)

I'm guessing this is just a helper script, but I would either mention this or completely remove it from the repo.

**Comment by kewljuice** [comment]
This is indeed a helper script for development purpose.
