### ISSUE TITLE
build.sh

### ISSUE THREAD

**Issue by Alienpruts** [kewljuice/maersk-line#2]
Is there any specific reason why the images need to be built locally instead of downloaded from a online repo, like Docker Hub?

I'm only mentioning it because there doesn't seem to be a security risk involved, or project specific configuration 'embedded' into the image(s).

That way you can directly use docker-compose to build the images (if needed), instead of introducing a manual step.

**Comment by kewljuice** [comment]
I removed the build.sh script, as of now the build process is included in the docker-compose file, we still need the images to extend the standard image(s) with packets like git, curl, etc.
