### ISSUE TITLE
cleanup.sh deletes ALL images / containers

### ISSUE THREAD

**Issue by Alienpruts** [kewljuice/maersk-line#3]
You do realize that if you execute cleanup.sh all images and containers will be removed, not only those specific to this project?

Just kidding, I saw it in the readme, however : this seems like a very dangerous thing to put in a shell script. 

My advice would be to leave image / container maintenance to the user and to not try to offer 'management services' to your users.

**Comment by kewljuice** [comment]
This is a helper script for development purpose, In upcoming releases I will remove this script.
